[build]
  command = "make build"
  functions = "functions"
  publish = "site/__sapper__/export/"
[build.environment]
  # Change this path with the path to your repository
  GO_IMPORT_PATH = "github.com/jeremyletang/chain-explorer-api"
  GO111MODULE = "on"
